[package]
name = "mmae200-project"
version = "0.1.0"
authors = ["bkeeneykid <bkeeneykid@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.0"
